---
# tasks file for wordpress
- name: 'Download WordPress'
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
  become: true

- name: 'Extract WordPress'
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www
    owner: www-data
    group: www-data
    remote_src: yes
  become: yes


